"use client";
import React, { useEffect, useState, useRef, memo } from "react";
import { motion } from "framer-motion";

const Digit = memo(function Digit({ char, shouldAnimate }: { char: string; shouldAnimate: boolean }) {
  const [animating, setAnimating] = useState(false);
  const prevChar = useRef(char);

  useEffect(() => {
    if (char !== prevChar.current && shouldAnimate) {
      setAnimating(true);
      const timer = setTimeout(() => setAnimating(false), 300);
      prevChar.current = char;
      return () => clearTimeout(timer);
    }
    prevChar.current = char;
  }, [char, shouldAnimate]);

  const isNumber = /\d/.test(char);

  return (
    <motion.span
      animate={animating ? {
        y: [0, -6, 0],
        opacity: [1, 0.4, 1],
      } : {}}
      transition={{ duration: 0.3, ease: [0.4, 0, 0.2, 1] }}
      className="inline-block"
      style={{ 
        width: isNumber ? "0.85em" : char === "," ? "0.28em" : "auto",
        textAlign: "center",
      }}
    >
      {char}
    </motion.span>
  );
});

function Counter({ value }: { value: number }) {
  const formatted = "$" + value.toLocaleString("en-US");
  const prevFormatted = useRef(formatted);
  const chars = formatted.split("");
  const prevChars = prevFormatted.current.split("");

  useEffect(() => {
    prevFormatted.current = formatted;
  }, [formatted]);

  return (
    <div 
      className="font-display text-white"
      style={{ 
        fontVariantNumeric: "tabular-nums",
        fontSize: "clamp(2.5rem, 9vw, 6rem)",
      }}
    >
      {chars.map((char, i) => {
        const prevChar = prevChars[i];
        const changed = prevChar !== char;
        return (
          <Digit 
            key={i} 
            char={char} 
            shouldAnimate={changed}
          />
        );
      })}
    </div>
  );
}

export default function UnderTheHood() {
  const [yieldTotal, setYieldTotal] = useState(2_847_293_156);
  const [tvl, setTvl] = useState(87_432_156_892);
  const yieldRef = useRef(2_847_293_156);
  const tvlRef = useRef(87_432_156_892);

  useEffect(() => {
    const yieldInterval = setInterval(() => {
      yieldRef.current += Math.floor(Math.random() * 50) + 10;
      setYieldTotal(yieldRef.current);
    }, 500);

    const tvlInterval = setInterval(() => {
      tvlRef.current += Math.floor(Math.random() * 2000000) - 500000;
      setTvl(tvlRef.current);
    }, 12000);

    return () => {
      clearInterval(yieldInterval);
      clearInterval(tvlInterval);
    };
  }, []);

  const formatBillions = (num: number) => {
    return (num / 1_000_000_000).toFixed(2);
  };

  return (
    <section className="py-32 lg:py-48 relative overflow-hidden">
      <div className="absolute inset-0 bg-[#0a0a0a]" />
      
      <div
        className="absolute inset-0 opacity-[0.2] pointer-events-none mix-blend-overlay"
        style={{
          backgroundImage: `url("data:image/svg+xml,%3Csvg viewBox='0 0 400 400' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noiseFilter'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noiseFilter)'/%3E%3C/svg%3E")`,
        }}
      />

      <div className="max-w-page mx-auto px-6 relative z-10">
        {/* Top section - Counters */}
        <div className="flex flex-col items-center text-center mb-24 lg:mb-32">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.8 }}
            className="mb-3"
          >
            <span className="text-white/30 text-sm uppercase tracking-widest">
              Total yield generated by DeFi
            </span>
            <div className="h-5" />
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.8, delay: 0.1 }}
            className="mb-8"
          >
            <Counter value={yieldTotal} />
          </motion.div>

          {/* TVL stat */}
          <motion.div
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            viewport={{ once: true }}
            transition={{ duration: 0.8, delay: 0.2 }}
            className="flex items-center gap-3"
          >
            <span className="text-white/30 text-sm">TVL</span>
            <span 
              className="text-white/50 text-sm font-mono"
              style={{ fontVariantNumeric: "tabular-nums" }}
            >
              ${formatBillions(tvl)}B
            </span>
          </motion.div>
        </div>

        {/* Bottom section - Non-custodial benefits */}
        <div className="grid lg:grid-cols-2 gap-16 lg:gap-24 items-start">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.8 }}
          >
            <h2
              className="font-display text-3xl sm:text-4xl lg:text-5xl text-white mb-6"
              style={{ WebkitFontSmoothing: "antialiased", textRendering: "geometricPrecision" }}
            >
              YOUR KEYS,<div className="h-4" /> <span className="text-brand">YOUR MONEY.</span>
            </h2>
            <p className="text-white/50 text-lg leading-relaxed">
              Yuki is fully non-custodial. We never hold your funds. Your money lives in smart contracts that only you control — not a company, not a bank, not us.
            </p>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.8, delay: 0.15 }}
            className="space-y-8"
          >
            {[
              {
                title: "No frozen accounts",
                description: "Banks and apps like Venmo can freeze your funds anytime. With Yuki, no one can lock you out of your own money.",
              },
              {
                title: "No withdrawal limits",
                description: "Cash App limits how much you can send. Banks make you wait days. Yuki has no limits — move any amount, instantly.",
              },
              {
                title: "No permission needed",
                description: "Traditional finance can decline transactions or close accounts without warning. Your Yuki wallet is yours forever.",
              },
            ].map((item, i) => (
              <motion.div
                key={item.title}
                initial={{ opacity: 0, x: 20 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.6, delay: 0.2 + i * 0.1 }}
              >
                <h3 className="text-white text-lg font-semibold mb-2">{item.title}</h3>
                <p className="text-white/40 leading-relaxed">{item.description}</p>
              </motion.div>
            ))}
          </motion.div>
        </div>
      </div>
    </section>
  );
}
