"use client";
import React, { useEffect, useState, useRef } from "react";
import { motion } from "framer-motion";

export default function UnderTheHood() {
  const [tvl, setTvl] = useState(87.4);
  const tvlRef = useRef(87.4);

  useEffect(() => {
    const tvlInterval = setInterval(() => {
      tvlRef.current += (Math.random() * 0.2) - 0.05;
      setTvl(tvlRef.current);
    }, 8000);

    return () => clearInterval(tvlInterval);
  }, []);

  return (
    <section className="py-20 sm:py-32 lg:py-48 relative overflow-hidden">
      <div className="absolute inset-0 bg-[#0a0a0a]" />
      
      <div
        className="absolute inset-0 opacity-[0.2] pointer-events-none mix-blend-overlay"
        style={{
          backgroundImage: `url("data:image/svg+xml,%3Csvg viewBox='0 0 400 400' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noiseFilter'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noiseFilter)'/%3E%3C/svg%3E")`,
        }}
      />

      <div className="max-w-page mx-auto px-4 sm:px-6 relative z-10">
        {/* Top section - DeFi stats */}
        <div className="flex flex-col items-center text-center mb-16 sm:mb-24 lg:mb-32">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.8 }}
            className="mb-4 sm:mb-6"
          >
            <span className="text-white/40 text-xs sm:text-sm uppercase tracking-widest">
              Total yield generated by DeFi
            </span>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.8, delay: 0.1 }}
            className="mb-6 sm:mb-8"
          >
            <span 
              className="font-headline text-white"
              style={{ 
                fontSize: "clamp(2.5rem, 10vw, 7rem)",
                WebkitFontSmoothing: "antialiased",
                textRendering: "geometricPrecision",
              }}
            >
              Over $3 billion
            </span>
          </motion.div>

          {/* TVL stat */}
          <motion.div
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            viewport={{ once: true }}
            transition={{ duration: 0.8, delay: 0.2 }}
            className="flex items-center gap-2 sm:gap-3"
          >
            <span className="text-white/40 text-xs sm:text-sm">TVL</span>
            <span className="text-white/60 text-xs sm:text-sm">
              ${tvl.toFixed(1)}B
            </span>
          </motion.div>
        </div>

        {/* Bottom section - Non-custodial benefits */}
        <div className="grid lg:grid-cols-2 gap-10 sm:gap-16 lg:gap-24 items-start">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.8 }}
          >
            <h2
              className="font-headline text-2xl sm:text-3xl lg:text-4xl xl:text-5xl text-white mb-4 sm:mb-6"
              style={{ WebkitFontSmoothing: "antialiased", textRendering: "geometricPrecision" }}
            >
              YOUR KEYS,<div className="h-2 sm:h-4" /> <span className="text-off">YOUR MONEY.</span>
            </h2>
            <p className="text-white/50 text-base sm:text-lg leading-relaxed">
              Yuki is fully non-custodial. We never hold your funds. Your money lives in smart contracts that only you control — not a company, not a bank, not us.
            </p>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.8, delay: 0.15 }}
            className="space-y-6 sm:space-y-8"
          >
            {[
              {
                title: "No frozen accounts",
                description: "Banks and apps like Venmo can freeze your funds anytime. With Yuki, no one can lock you out of your own money.",
              },
              {
                title: "No withdrawal limits",
                description: "Cash App limits how much you can send. Banks make you wait days. Yuki has no limits — move any amount, instantly.",
              },
              {
                title: "No permission needed",
                description: "Traditional finance can decline transactions or close accounts without warning. Your Yuki wallet is yours forever.",
              },
            ].map((item, i) => (
              <motion.div
                key={item.title}
                initial={{ opacity: 0, x: 20 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.6, delay: 0.2 + i * 0.1 }}
              >
                <h3 className="text-white text-base sm:text-lg font-semibold mb-1.5 sm:mb-2">{item.title}</h3>
                <p className="text-white/40 text-sm sm:text-base leading-relaxed">{item.description}</p>
              </motion.div>
            ))}
          </motion.div>
        </div>
      </div>
    </section>
  );
}
